### ISSUE TITLE
bug #18086: compilation failed due to epoll_create1 not present

### ISSUE THREAD

**Issue by BharatDBPG** [BharatDBPG/BharatDBMS-PG#2518]
**📨 Subject**: BUG #18086: compilation failed due to epoll_create1 not present

**📅 Date:** 2023-09-05 10:59:54
**📤 Sender:** PG Bug reporting form <noreply(at)postgresql(dot)org>
**📥 Receiver:** pgsql-bugs(at)lists(dot)postgresql(dot)org
**📮 Message ID:** `18086-345129dec3223b38@postgresql.org`

**📝 Message :**
The following bug has been logged on the website:

Bug reference: 18086  
Logged by: Duke Astar  
Email address: dukeastar(at)gmail(dot)com  
PostgreSQL version: 14.9  
Operating system: Linux x86  
Description: 

Operating system: CentOS release 5.8 (Final) - Linux dev-linuxx86  
2.6.18-308.el5 \#1 SMP Tue Feb 21 20:05:41 EST 2012 i686 i686  
Build options: from source code using default options for 'configure'

during make, compilation failed due to missing epoll_create1, compilation  
works in postgres 13.12

Below the error.  
latch.c  
latch.c: In function ‘CreateWaitEventSet’:  
latch.c:763: warning: implicit declaration of function ‘epoll_create1’  
latch.c:763: error: ‘EPOLL_CLOEXEC’ undeclared (first use in this  
function)  
latch.c:763: error: (Each undeclared identifier is reported only once  
latch.c:763: error: for each function it appears in.)  
make[4]: *** [latch.o] Error 1  
make[4]: Leaving directory  
`/home2/ctaillef/pgdbg/libs/postgresql-14.9/src/backend/storage/ipc'  
make[3]: *** [ipc-recursive] Error 2  
make[3]: Leaving directory  
`/home2/ctaillef/pgdbg/libs/postgresql-14.9/src/backend/storage'  
make[2]: *** [storage-recursive] Error 2  
make[2]: Leaving directory  
`/home2/ctaillef/pgdbg/libs/postgresql-14.9/src/backend'  
make[1]: *** [all-backend-recurse] Error 2  
make[1]: Leaving directory  
`/home2/ctaillef/pgdbg/libs/postgresql-14.9/src'  
make: *** [all-src-recurse] Error 2

configure set macro HAVE_SYS_EPOLL_H when sys/epoll.h is present  
and in src/backend/storageipc/latch.c   
HAVE_SYS_EPOLL_H define WAIT_USE_EPOLL   
and WAIT_USE_EPOLL use have 'epoll_create1' which is not present on the  
operating system, only first version is present 'epoll_create'

I compared source code between 13.2 and 14.9 and I saw the ifdef  
EPOLL_CLOEXEC section was removed, which was a previous constraint which use  
epoll_create if not defined instead of epoll_create1 .

Workaround   
As a workaround I found that i can set -DWAIT_USE_POLL during configure to  
use poll instead epoll but I think that's lead to performance issue.

Thanks by advance,  
Regards

**Comment by BharatDBPG** [comment]
**📨 Subject:** Re: BUG #18086: compilation failed due to epoll_create1 not present


**📅 Date:** 2023-09-05 11:51:28
**📤 Sender:** Daniel Gustafsson <daniel(at)yesql(dot)se>
**📥 Receiver:** dukeastar(at)gmail(dot)com,
 pgsql-bugs(at)lists(dot)postgresql(dot)org
**📮 Message ID:** `73E70C7A-1A86-4A8B-8CA8-8FB5D11509EC@yesql.se`

**📝 Message:**
> On 5 Sep 2023, at 12:59, PG Bug reporting form <noreply(at)postgresql(dot)org> wrote:

> during make, compilation failed due to missing epoll_create1, compilation  
> works in postgres 13.12

...

> configure set macro HAVE_SYS_EPOLL_H when sys/epoll.h is present  
> and in src/backend/storageipc/latch.c   
> HAVE_SYS_EPOLL_H define WAIT_USE_EPOLL   
> and WAIT_USE_EPOLL use have 'epoll_create1' which is not present on the  
> operating system, only first version is present 'epoll_create'  
>   
> I compared source code between 13.2 and 14.9 and I saw the ifdef  
> EPOLL_CLOEXEC section was removed, which was a previous constraint which use  
> epoll_create if not defined instead of epoll_create1 .  
>   
> Workaround   
> As a workaround I found that i can set -DWAIT_USE_POLL during configure to  
> use poll instead epoll but I think that's lead to performance issue.

Commit d1b90995e8d41df7e59efe48e98f26cd66baba9b and the pgsql-hackers thread  
<https://postgr.es/m/CA+hUKGKL_=aO=r30N=s9VoDgTqHpRSzePRbA9dkYO7snc7HsxA@mail.gmail.com>  
provides background on that removal. RHEL 5 is not a supported target.

\--  
Daniel Gustafsson
