### ISSUE TITLE
bug #18058: http extension postgres

### ISSUE THREAD

**Issue by BharatDBPG** [BharatDBPG/BharatDBMS-PG#2487]
**📨 Subject**: BUG #18058: Http Extension Postgres

**📅 Date:** 2023-08-16 06:32:40
**📤 Sender:** PG Bug reporting form <noreply(at)postgresql(dot)org>
**📥 Receiver:** pgsql-bugs(at)lists(dot)postgresql(dot)org
**📮 Message ID:** `18058-bc755c5675ed6343@postgresql.org`

**📝 Message :**
The following bug has been logged on the website:

Bug reference: 18058  
Logged by: Postgres  
Email address: smarttown2547(at)gmail(dot)com  
PostgreSQL version: 15.4  
Operating system: Ubuntu  
Description: 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement  
-Werror=vla -Wendif-labels -Wmissing-format-attribute  
-Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security  
-fno-strict-aliasing -fwrapv -fexcess-precision=standard  
-Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -flto=auto  
-ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong  
-Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./  
-I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal   
-Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -c -o  
http.o http.c  
http.c: In function ‘typname_get_tupledesc’:  
http.c:594:63: error: macro "GetSysCacheOid2" requires 4 arguments, but only  
3 given  
594 | ObjectIdGetDatum(typnamespace));  
| ^  
In file included from http.c:59:  
/usr/include/postgresql/15/server/utils/syscache.h:199: note: macro  
"GetSysCacheOid2" defined here  
199 | #define GetSysCacheOid2(cacheId, oidcol, key1, key2) \  
|  
http.c:592:30: error: ‘GetSysCacheOid2’ undeclared (first use in this  
function); did you mean ‘GetSysCacheOid’?  
592 | Oid typoid = GetSysCacheOid2(TYPENAMENSP,  
| ^~~~~~~~~~~~~~~  
| GetSysCacheOid  
http.c:592:30: note: each undeclared identifier is reported only once for  
each function it appears in  
http.c:591:21: warning: unused variable ‘typnamespace’ [-Wunused-variable]  
591 | Oid typnamespace = lfirst_oid(l);  
| ^~~~~~~~~~~~  
make: *** [<builtin>: http.o] Error 1  
We tried all setups but the http extension does not work with Postgres 15.4.  
so please guild us.
